const stores = [
  {
    id: 1,
    name: 'Matsuri Concept',
    deliveryAmount: 0,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 2,
    name: 'Subway - Avenida Center',
    deliveryAmount: 6,
    rating: 4.7,
    isOpen: true,
    logoUrl:
      'https://filecache.mediaroom.com/mr5mr_subway/178093/Subway%20Hi-Res%20Logo_asset_thumbnail.png',
  },
  {
    id: 3,
    name: 'Burger King - Colombo',
    deliveryAmount: 11.99,
    rating: 4.7,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 4,
    name: 'Pizza Prime - Centro',
    deliveryAmount: 0,
    rating: 4.5,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 5,
    name: 'China Box - Shopping',
    deliveryAmount: 0,
    rating: 4.3,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 6,
    name: 'Açai da Hora',
    deliveryAmount: 4,
    rating: 4.8,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 7,
    name: 'Pastel do Zé',
    deliveryAmount: 3.99,
    rating: 4.2,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 8,
    name: "Domino's Pizza - Norte",
    deliveryAmount: 0,
    rating: 4.6,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 9,
    name: 'Café Brasiliano',
    deliveryAmount: 2,
    rating: 4.9,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 10,
    name: 'Churrasquinho do Tonho',
    deliveryAmount: 6.5,
    rating: 4.4,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 11,
    name: "McDonald's - Centro",
    deliveryAmount: 0,
    rating: 4.6,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 12,
    name: 'Starbucks - Shopping',
    deliveryAmount: 4.5,
    rating: 4.8,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 13,
    name: 'KFC - Avenida Brasil',
    deliveryAmount: 6,
    rating: 4.5,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 14,
    name: 'Pizza Hut - Centro',
    deliveryAmount: 7,
    rating: 4.4,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 15,
    name: 'Taco Bell - Shopping',
    deliveryAmount: 0,
    rating: 4.3,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 16,
    name: "Dunkin' Donuts - Centro",
    deliveryAmount: 3.5,
    rating: 4.6,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 17,
    name: "Wendy's - Avenida Paulista",
    deliveryAmount: 6.5,
    rating: 4.5,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 18,
    name: "Papa John's - Centro",
    deliveryAmount: 7.5,
    rating: 4.4,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 19,
    name: 'Chipotle - Shopping',
    deliveryAmount: 5.99,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 20,
    name: "Bob's - Centro",
    deliveryAmount: 4.99,
    rating: 4.3,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
];

export default stores;
