const stores = [
  {
    id: 1,
    name: 'Matsuri Concept',
    deliveryAmount: 0,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 2,
    name: 'Subway - Avenida Center',
    deliveryAmount: 6,
    rating: 4.7,
    isOpen: true,
    logoUrl:
      'https://filecache.mediaroom.com/mr5mr_subway/178093/Subway%20Hi-Res%20Logo_asset_thumbnail.png',
  },
  {
    id: 3,
    name: 'Burger King - Colombo',
    deliveryAmount: 11.99,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 4,
    name: 'Pizza Prime - Centro',
    deliveryAmount: 0,
    rating: 4.5,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 5,
    name: 'China Box - Shopping',
    deliveryAmount: 0,
    rating: 4.3,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 6,
    name: 'Açai da Hora',
    deliveryAmount: 4,
    rating: 4.8,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 7,
    name: 'Pastel do Zé',
    deliveryAmount: 3.99,
    rating: 4.2,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 8,
    name: "Domino's Pizza - Norte",
    deliveryAmount: 0,
    rating: 4.6,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 9,
    name: 'Café Brasiliano',
    deliveryAmount: 2,
    rating: 4.9,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
  {
    id: 10,
    name: 'Churrasquinho do Tonho',
    deliveryAmount: 6.5,
    rating: 4.4,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
  },
];

export default stores;
