const detailedStores = [
  {
    id: 1,
    name: 'Matsuri Concept',
    deliveryAmount: 0,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 2,
    name: 'Subway - Avenida Center',
    deliveryAmount: 6,
    rating: 4.7,
    isOpen: true,
    logoUrl:
      'https://filecache.mediaroom.com/mr5mr_subway/178093/Subway%20Hi-Res%20Logo_asset_thumbnail.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 3,
    name: 'Burger King - Colombo',
    deliveryAmount: 11.99,
    rating: 4.7,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [
      {
        name: 'Niguiris',
        description: undefined,
        promotion: true,
        foods: [
          {
            name: 'Niguiri de Salmão',
            description: 'Arroz japonês coberto com fatia de salmão fresco',
            price: 9.99,
            initialPrice: true,
            promotionPrice: undefined,
            details: [],
          },
          {
            name: 'Niguiri de Atum',
            description: 'Arroz japonês coberto com fatia de atum fresco',
            price: 10.99,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
          {
            name: 'Niguiri de Camarão',
            description: 'Arroz japonês com camarão cozido e molho tarê',
            price: 11.99,
            initialPrice: false,
            promotionPrice: 9.99,
            details: [],
          },
        ],
      },
      {
        name: 'Ceviches',
        description:
          'um prato super refrescante de peixe fatiado e marinado com limão',
        promotion: true,
        foods: [
          {
            name: 'Ceviche Clássico',
            description:
              'Cenoura marinada no limão com cebola roxa, coentro e pimenta dedo-de-moça',
            price: 19.99,
            initialPrice: false,
            promotionPrice: undefined,
            details: ['Picante', 'Vegetariano'],
          },
          {
            name: 'Ceviche de Salmão',
            description:
              'Cubos de salmão fresco marinados com limão, cebola roxa, manga e hortelã',
            price: 22.99,
            initialPrice: true,
            promotionPrice: undefined,
            details: [],
          },
        ],
      },
      {
        name: 'Temakis',
        description: 'sushi em forma de cone com salmão e cream cheese',
        promotion: false,
        foods: [
          {
            name: 'Califórnia',
            description: 'Kani, pepino e maçã ou manga',
            price: 17,
            initialPrice: false,
            promotionPrice: 13.99,
            details: [],
          },
          {
            name: 'Califórnia',
            description: 'Kani, pepino e maçã ou manga',
            price: 13.99,
            initialPrice: false,
            promotionPrice: undefined,
            details: ['Vegetariano'],
          },
          {
            name: 'Filadélfia',
            description: 'Arroz, salmão fresco, cream cheese e cebolinha',
            price: 13.99,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
          {
            name: 'Mix',
            description:
              'Escolha 3 ingredientes: shimeji, alface americana, rúcula, pepino, tomate seco, cream cheese, maionese, goiabada, banana, requeijão, molho de maracujá, manga, maçã e morango.',
            price: 13.99,
            initialPrice: true,
            promotionPrice: undefined,
            details: ['Picante'],
          },
          {
            name: 'Salmão picante',
            description: 'Alga, arroz, salmão fresco, pimenta e cebolinha',
            price: 13.99,
            initialPrice: true,
            promotionPrice: undefined,
            details: ['Picante'],
          },
        ],
      },
      {
        name: 'Bebidas',
        description: undefined,
        promotion: false,
        foods: [
          {
            name: 'Coca Lata',
            description: undefined,
            price: 5,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
          {
            name: 'Guaraná Lata',
            description: undefined,
            price: 4.5,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
          {
            name: 'Coca 2L',
            description: undefined,
            price: 12,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
        ],
      },
      {
        name: 'Sobremesas',
        description: undefined,
        promotion: false,
        foods: [
          {
            name: 'Sorvete de copo',
            description:
              'Escolha até 2 bolas de diferentes tipos de sabores de sorvete',
            price: 11,
            initialPrice: false,
            promotionPrice: undefined,
            details: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Pizza Prime - Centro',
    deliveryAmount: 0,
    rating: 4.5,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 5,
    name: 'China Box - Shopping',
    deliveryAmount: 0,
    rating: 4.3,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 6,
    name: 'Açai da Hora',
    deliveryAmount: 4,
    rating: 4.8,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 7,
    name: 'Pastel do Zé',
    deliveryAmount: 3.99,
    rating: 4.2,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 8,
    name: "Domino's Pizza - Norte",
    deliveryAmount: 0,
    rating: 4.6,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 9,
    name: 'Café Brasiliano',
    deliveryAmount: 2,
    rating: 4.9,
    isOpen: true,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
  {
    id: 10,
    name: 'Churrasquinho do Tonho',
    deliveryAmount: 6.5,
    rating: 4.4,
    isOpen: false,
    logoUrl: 'https://pngimg.com/uploads/burger_king/burger_king_PNG13.png',
    closingTime: '20:00',
    minimumOrder: 15,
    categories: [],
  },
];

export default detailedStores;
